### ISSUE TITLE
code

### ISSUE THREAD

**Issue by zhenyuan1234** [FreeButUselessSoul/occ-nerf#1]
Hello，when to release the complete code，thanks！

**Comment by FreeButUselessSoul** [comment]
The complete code is already available in this repo, and we will update the way to run it in the coming days.

**Comment by zhenyuan1234** [comment]
你好，最近拜读了您的这项CVPR2023的工作，我对您的工作非常感兴趣，请问您能解答一下如何去训练和测试这个模型吗，非常感谢！
| |
yjqiao58
|
|
***@***.***
|
---- Replied Message ----
| From | Chengxuan ***@***.***> |
| Date | 6/26/2023 08:52 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [FreeButUselessSoul/occ-nerf] code (Issue #1) |

The complete code is already available in this repo, and we will update the way to run it in the coming days.
