### ISSUE TITLE
train_homo_back_sigma.py和train_maskLD_long.py两个文件有什么不同呢

### ISSUE THREAD

**Issue by Shzhuoyu** [FreeButUselessSoul/occ-nerf#4]
在您local1.txt文件所说的train_homo_back_sigma.py和README.md里面所说的train_maskDL_long.py，这两个文件有什么区别呢。如果我希望复现您论文结果，我应该跑哪一个文件？谢谢您～

**Comment by Abbsalehi** [comment]
see here #6

**Comment by FreeButUselessSoul** [comment]
Redundant files are deleted recently, for a clearer understanding.

**Comment by Shzhuoyu** [comment]
Thanks！
