### ISSUE TITLE
What is the difference between python file inside "homo" folder?

### ISSUE THREAD

**Issue by Abbsalehi** [FreeButUselessSoul/occ-nerf#6]
I would like to know the difference between the Python files located inside the "homo" folder. For instance, what is the specific purpose of each file? The explanation present in your code is very unclear, which makes it difficult to reproduce your work and cite it accurately. 

```
train_homo_back_sigma.py
train_homo_maskDL.py
train_maskDL_FT.py
train_maskDL_long.py
```

**Comment by FreeButUselessSoul** [comment]
Apologies for the confusion. The redundant files are used for debugging purpose only, and will be cleaned up in the comming release. As suggested in the quick start part, only `train_maskDL_long.py` is needed for training.
