### ISSUE TITLE
 Dataset does not produce results when run on COLMAP

### ISSUE THREAD

**Issue by Shzhuoyu** [FreeButUselessSoul/occ-nerf#9]
When I use the latest COLMAP version 3.8 with the LLFF code (img2pose.py), it fails to produce results on your dataset. Could you please let me know which version or command the author used to run it?

**Comment by wanzhouliu** [comment]
I met the same problem. Could you please share how to solve it? Thanks!

**Comment by Shzhuoyu** [comment]
> I met the same problem. Could you please share how to solve it? Thanks!

没有，我建议你自己拍数据集
